apiVersion: v1
clusters:
- cluster:
    certificate-authority: /srv/kubernetes/ca.pem
    server: https://172.17.157.121:6443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    user: default-admin
  name: default-system
current-context: default-system
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate: /srv/kubernetes/admin.pem
    client-key: /srv/kubernetes/admin-key.pem
